# ParentID: 2
# ObjectID: 0
# Character field ID when accessed: 101070100
# Portal Position Y: 199
# Portal Position X: -146

FANZYS_MAGIC_2 = 32104 # QUEST ID
MIDSUMMER_NIGHTS_FOREST_ELLINEL_LAKE_SHORE = 101070000 # MAP ID
MIDSUMMER_NIGHTS_FOREST_ELLINEL_LAKE_SHORE_2 = 101070010 # MAP ID

if sm.hasQuestCompleted(FANZYS_MAGIC_2):
    sm.warp(MIDSUMMER_NIGHTS_FOREST_ELLINEL_LAKE_SHORE_2, 2)
else:
    sm.warp(MIDSUMMER_NIGHTS_FOREST_ELLINEL_LAKE_SHORE, 1)